sonar.projectKey=yurake_pptx_generator
sonar.projectName=pptx_generator
sonar.organization=yurak
sonar.host.url=https://sonarcloud.io

sonar.sources=src
sonar.tests=tests
sonar.exclusions=**/__pycache__/**,**/.venv/**,dotnet/**/bin/**,dotnet/**/obj/**
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
sonar.coverage.exclusions=tests/**,dotnet/Polisher.Tests/**
