"""`pptx_generator.models` パッケージ。

従来の `models.py` で定義されていたクラスを責務別モジュールに再編し、
ここでまとめて再エクスポートしている。既存コードからは
`from pptx_generator.models import Foo` のまま利用できる。
"""

from __future__ import annotations

from .common import (
    DEFAULT_JP_FONT,
    FontSpec,
    TemplateChartDefaults,
    TemplateColorPalette,
    TemplateImageDefaults,
    TemplateStyle,
    TemplateTableDefaults,
    TemplateTextboxDefaults,
    TextCapacity,
    TextFramePadding,
    TextboxParagraph,
    TextboxPosition,
)
from .content import (
    AIReviewIssue,
    AIReviewResult,
    AutoFixProposal,
    ContentApprovalDocument,
    ContentDocumentMeta,
    ContentElements,
    ContentReviewLogEntry,
    ContentSlide,
    ContentSlideSource,
    ContentSlideStatus,
    ContentTableData,
    JsonPatchOp,
    JsonPatchOperation,
)
from .draft import (
    DraftAnalyzerSummary,
    DraftDocument,
    DraftLayoutCandidate,
    DraftLayoutScoreDetail,
    DraftLogEntry,
    DraftMeta,
    DraftSection,
    DraftSlideCard,
    DraftStatus,
    DraftTemplateMismatch,
)
from .exceptions import PipelineFallbackError, SpecValidationError
from .jobs import (
    JobAuth,
    JobMeta,
    JobSpec,
    JobSpecScaffold,
    JobSpecScaffoldBounds,
    JobSpecScaffoldMeta,
    JobSpecScaffoldPlaceholder,
    JobSpecScaffoldPlaceholderKind,
    JobSpecScaffoldSlide,
)
from .mapping import (
    GenerateReadyDocument,
    GenerateReadyMeta,
    GenerateReadySlide,
    MappingAIPatch,
    MappingCandidate,
    MappingFallbackState,
    MappingLog,
    MappingLogCapacityWarning,
    MappingLogAnalyzerIssue,
    MappingLogAnalyzerSummary,
    MappingLogMeta,
    MappingLogSlide,
    MappingSlideMeta,
)
from .slides import (
    ChartOptions,
    ChartSeries,
    Slide,
    SlideBullet,
    SlideBulletGroup,
    SlideChart,
    SlideImage,
    SlideTable,
    SlideTextbox,
    TableStyle,
)
from .template import (
    LayoutInfo,
    ShapeInfo,
    TemplateBlueprint,
    TemplateBlueprintSlide,
    TemplateBlueprintSlot,
    TemplateSpec,
)

__all__ = [
    # common
    "DEFAULT_JP_FONT",
    "FontSpec",
    "TextboxPosition",
    "TextboxParagraph",
    "TextFramePadding",
    "TextCapacity",
    "TemplateColorPalette",
    "TemplateTextboxDefaults",
    "TemplateTableDefaults",
    "TemplateChartDefaults",
    "TemplateImageDefaults",
    "TemplateStyle",
    # slides
    "SlideBullet",
    "SlideBulletGroup",
    "SlideImage",
    "TableStyle",
    "SlideTable",
    "ChartSeries",
    "ChartOptions",
    "SlideChart",
    "SlideTextbox",
    "Slide",
    # jobs
    "JobMeta",
    "JobAuth",
    "JobSpec",
    "JobSpecScaffoldBounds",
    "JobSpecScaffoldPlaceholder",
    "JobSpecScaffoldSlide",
    "JobSpecScaffoldMeta",
    "JobSpecScaffold",
    "JobSpecScaffoldPlaceholderKind",
    # content
    "ContentTableData",
    "ContentElements",
    "JsonPatchOp",
    "JsonPatchOperation",
    "AutoFixProposal",
    "AIReviewIssue",
    "AIReviewResult",
    "ContentSlideSource",
    "ContentSlide",
    "ContentDocumentMeta",
    "ContentApprovalDocument",
    "ContentReviewLogEntry",
    "ContentSlideStatus",
    # draft
    "DraftStatus",
    "DraftLayoutCandidate",
    "DraftLayoutScoreDetail",
    "DraftAnalyzerSummary",
    "DraftSlideCard",
    "DraftSection",
    "DraftTemplateMismatch",
    "DraftMeta",
    "DraftDocument",
    "DraftLogEntry",
    # mapping
    "MappingSlideMeta",
    "GenerateReadySlide",
    "GenerateReadyMeta",
    "GenerateReadyDocument",
    "MappingCandidate",
    "MappingFallbackState",
    "MappingAIPatch",
    "MappingLogCapacityWarning",
    "MappingLogAnalyzerIssue",
    "MappingLogAnalyzerSummary",
    "MappingLogSlide",
    "MappingLogMeta",
    "MappingLog",
    # exceptions
    "SpecValidationError",
    "PipelineFallbackError",
    # template
    "ShapeInfo",
    "LayoutInfo",
    "TemplateBlueprintSlot",
    "TemplateBlueprintSlide",
    "TemplateBlueprint",
    "TemplateSpec",
]
