name: todo-sync

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/todo/*.md'
  schedule:
    - cron: '15 * * * *'  # 毎時15分（任意）
  issues:
    types: [opened, edited, closed, reopened, labeled, unlabeled]

permissions:
  contents: write
  issues: write

jobs:
  from_md:
    name: Sync from template.md → Issues
    if: >-
      github.event_name != 'push' ||
      !contains(github.event.head_commit.message, '[skip md->issues]')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Sync template.md → Issues (create/close + parent link injection)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          python scripts/sync_todo_to_issues.py --todo-path docs/todo/template.md --label 'todo-sync' --parent-label 'todo-card'
      - name: Commit parent-issue link if inserted
        run: |
          if git diff --quiet; then
            echo 'No changes to commit from from_md.'
          else
            git config user.name 'github-actions[bot]'
            git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
            git add docs/todo/template.md
            git commit -m 'chore(todo): link parent issue in template.md [skip md->issues]'
            git push
          fi

  from_issues:
    name: Sync from Issues → template.md
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Build template.md from Issues
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          python scripts/sync_issues_to_todo.py --todo-path docs/todo/template.md --label 'todo-sync'
      - name: Commit & Push if changed
        run: |
          if git diff --quiet; then
            echo 'No changes.'
          else
            git config user.name 'github-actions[bot]'
            git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
            git add docs/todo/template.md
            git commit -m 'chore(todo): sync Issues → template.md [skip md->issues]'
            git push
          fi
